### ISSUE TITLE
Unreal Engine 5 と VSCodeでの開発環境構築

### ISSUE THREAD

**Issue by ide-jun** [Kosuke-Sugimoto/m1-game-dev#6]
VSCodeを使ったUnreal Engineゲーム開発を、Visual Studioをインストールせずに行う事ができる。

「Visual Studio Build Tools 2022」から必要なビルドツールのみをインストールするだけで良いらしい。

以下にやり方を掲載：

### 環境構築方法
1. Unreal Engine 5のインストール
  - https://zenn.dev/posita33/books/ue5_starter_cpp_and_bp_001/viewer/chap_01_ue5_install を参照
2. VSCodeのセットアップ
- https://zenn.dev/posita33/books/ue5_starter_cpp_and_bp_001/viewer/chap_01_vscode_setup を参照
- 「Visual Studio Build Tools 2022」をインストールする際に、
「個別のコンポーネント」から「.NET Framework 4.8.1 SDK」をインストール
  - これがないと、Unreal EngineでC++プロジェクトを立ち上げた際にエラーが起きる！
<img width="960" alt="image" src="https://github.com/Kosuke-Sugimoto/m1-game-dev/assets/83441165/c5a7409f-f359-4d1f-ad3e-901e25660266">

**Comment by Kosuke-Sugimoto** [comment]
開発環境の構築ができることは確認できたのでcloseします。
GitHubとの連携について別Issueでお願いします
